from pathlib import Path
root=Path(r'C:\Mockaroo')
src=root/'history'; out=root/'Question Bank'/'history'; out.mkdir(parents=True,exist_ok=True)
chapters={
1:('Stone Age','stone_age',['Palaeolithic means Old Stone Age and preceded the Mesolithic','Bhimbhetka rock caves were discovered by V. S. Wakankar in 1957','Mesolithic humans were hunters and herders and domestication of animals began in this period','Flake technology involved striking a stone core to remove flakes']),
2:('Indus Valley Civilization','indus_valley_civilization',['Harappan seals were made of steatite and often carried animal motifs','Harappan roads intersected at right angles in a grid pattern','Harappan script was pictographic, written from right to left, and remains undeciphered','Chanhudaro was a centre of bead making, shell cutting, metal working, seal making and weights']),
3:('Vedic Age','vedic_age',['The Early Vedic Age is dated 1500–1000 BC and was pastoral','The Rig Veda was the first Veda compiled and has 10 mandalas','The Battle of Ten Kings was fought on the Purushini (Ravi) and was won by Bharata chief Sudas','In the Later Vedic period iron and horses helped expansion from Punjab towards eastern Uttar Pradesh']),
4:('Jainism and Buddhism','jainism_and_buddhism',['Mahavira was the 24th Tirthankara and was born at Kundagram near Vaishali','The Four Noble Truths identify desire as the cause of suffering and the Eightfold Path as the way to end it','The Third Buddhist Council was held at Pataliputra under Ashoka and presided over by Moggaliputta Tissa','The Fourth Buddhist Council under Kanishka at Kashmir led to the division into Mahayana and Hinayana']),
5:('Mahajanpadas','mahajanpadas',['Sixteen Mahajanapadas are mentioned in Anguttara Nikaya','The capital of Vatsa was Kausambi','Magadha rose due to iron mines, elephants, strategic position and capable rulers','Udayin shifted the capital of Magadha from Rajgriha to Pataliputra']),
6:('Maurya Dynasty','maurya_dynasty',['Chandragupta Maurya founded the Mauryan Dynasty in 322 BCE with Kautilya','Megasthenes was sent as ambassador to Chandragupta Maurya’s court at Pataliputra','Ashoka fought the Kalinga War in 261 BCE and replaced Bherighosha with Dhammaghosha','James Prinsep was the first to decipher Ashokan inscriptions in 1837']),
7:('Post-Maurya Dynasties','post_maurya_dynasties',['Pushyamitra Shunga founded the Shunga Dynasty after killing Brihadratha Maurya','The Satavahana capital was Paithan or Pratisthan','Menander (Milinda) was an Indo-Greek ruler whose dialogue with Nagasena is Milindapanho','Kanishka started the Saka Era in 78 AD and patronised the Fourth Buddhist Council']),
8:('Gupta Dynasty','gupta_dynasty',['Sri Gupta was the founder of the Gupta Dynasty','Samudragupta’s achievements are recorded in the Prayag Prasasti composed by Harisena','Chandragupta II took the title Vikramaditya after defeating the Sakas','Kumaragupta I founded Nalanda University']),
9:('Post-Gupta Dynasties','post_gupta_dynasties',['Harshavardhana made Kannauj his capital and ruled from 606 to 647 AD','Pulakeshin II defeated Harshavardhana on the banks of the Narmada','The Badami Chalukya capital was Vatapi','Dantidurga founded the Rashtrakuta Dynasty and their capital was Manyakheta']),
10:('Sangam Age','sangam_age',['The three Sangams were patronised by the Pandyas','Tolkappiyam was the earliest grammatical Tamil text and is associated with Tolkappiyar','The Chera capital was Vanji and its emblem was a bow and arrow','The Pandya capital was Madurai and its emblem was fish']),
11:('Tripartite Struggle and Cholas','tripartite_struggle_and_cholas',['The Tripartite Struggle for Kannauj was between Palas, Pratiharas and Rashtrakutas','Vijayalaya Chola founded the later Chola Dynasty and captured Tanjore','Raja Raja I built the Brihadeeshwara Temple at Tanjore','Rajendra I took the title Gangaikondachola after crossing the Ganga']),
12:('Delhi Sultanate','delhi_sultanate',['The Delhi Sultanate lasted from 1206 to 1526 AD','The First Battle of Tarain in 1191 was won by Prithviraj Chauhan and the Second in 1192 by Muhammad Ghori','Qutb-ud-din Aibak was called Lakh Baksh and ruled from Lahore','Ibrahim Lodi was the last ruler of the Delhi Sultanate and lost to Babur at Panipat in 1526']),
13:('Vijayanagara and Bahmani Kingdom','vijayanagara_and_bahmani_kingdom',['Harihara and Bukka founded the Vijayanagara Empire in 1336 and its capital was Hampi','Krishna Deva Raya belonged to the Tuluva Dynasty and ruled from 1509 to 1529','Ala-ud-din Hasan Bahman Shah founded the Bahmani Kingdom with Gulbarga as its first capital','Ahmad Shah Wali shifted the Bahmani capital from Gulbarga to Bidar']),
14:('Mughal Empire','mughal_empire',['Babur founded the Mughal Dynasty after defeating Ibrahim Lodi in the First Battle of Panipat in 1526','Sher Shah Suri introduced the Rupia and gave peasants Patta and Qabuliyat','Akbar abolished the Jizya in 1564 and introduced the Mansabdari system','Aurangzeb reimposed Jizya in 1679 and was the last major Mughal emperor']),
15:('Marathas','marathas',['Shivaji was crowned Chhatrapati at Raigad in 1674','The Treaty of Purandar (1665) required Shivaji to surrender 23 forts to the Mughals','Chauth was one-fourth of land revenue and Sardeshmukhi was an additional ten percent','The Third Battle of Panipat in 1761 was fought between Marathas and Ahmad Shah Abdali']),
16:('Bhakti and Sufi Movements','bhakti_and_sufi_movements',['Kabir belonged to the Nirguna sect and Bijaka compiles his preachings','Ramanuja propounded Vishishtadvaita while Madhva propounded Dvaita','Guru Angad introduced the Gurmukhi script','Guru Gobind Singh established the Khalsa Panth on Vaisakhi in 1699']),
17:('Advent of Europeans','advent_of_europeans',['Vasco da Gama reached Calicut in 1498 during the rule of Zamorin','The Dutch East India Company was formed in 1602 and set up its first factory at Masulipatnam','The English first established a permanent factory at Surat in 1613','The Battle of Plassey in 1757 confirmed the formal beginning of British rule in India']),
18:('Socio-Religious Reforms','socio_religious_reforms',['Swami Dayanand Saraswati founded Arya Samaj in 1875 and wrote Satyarth Prakash','Sir Syed Ahmad Khan started the Aligarh Movement and the Mohammedan Anglo Oriental College','Jyotiba Phule founded Satyashodhak Samaj in 1873 against caste discrimination','Swami Vivekananda founded Ramakrishna Mission in 1897 with headquarters at Belur Math']),
19:('Revolt of 1857','revolt_of_1857',['The Revolt of 1857 began at Meerut on 10 May 1857','Mangal Pandey attacked British officers at Barrackpore on 29 March 1857','Rani Lakshmibai led the revolt at Jhansi while Kunwar Singh led it in Bihar','The Government of India Act 1858 ended Company rule and made the Governor-General the Viceroy']),
20:('Bengal Partition','bengal_partition',['Lord Curzon proposed the Partition of Bengal in 1905','The partition came into force in October 1905 after being announced in July','The Swadeshi Movement formally began at Calcutta Town Hall on 7 August 1905','The Partition of Bengal was annulled in 1911 and the capital shifted from Calcutta to Delhi']),
21:('Gandhian Era','gandhian_era',['Gandhi returned to India on 9 January 1915 and Gopal Krishna Gokhale was his political guru','Champaran Satyagraha (1917) opposed the Tinkathia system of indigo cultivation','The Non-Cooperation Movement was withdrawn after the Chauri Chaura incident in 1922','The Swaraj Party was formed in 1923 by C. R. Das and Motilal Nehru']),
22:('CDM and Simon Commission','cdm_and_simon_commission',['The Simon Commission arrived in India in 1928 without any Indian member','Lala Lajpat Rai was injured during a protest against Simon Commission and later died','The Civil Disobedience Movement began with Gandhi’s Salt March from Sabarmati to Dandi in 1930','The Gandhi-Irwin Pact was signed in 1931 before the Second Round Table Conference']),
23:('Quit India Movement','quit_india_movement',['The Quit India Resolution was adopted at Wardha in July 1942 and ratified at Bombay','Gandhi launched the Quit India Movement on 8 August 1942 with the slogan Do or Die','The movement became leaderless after its leaders were arrested on the first day','Usha Mehta ran an underground radio in Bombay during the movement'])}

def opts(correct, pool, i):
    # rotate correct position deterministically
    wrong=[x for x in pool if x!=correct][:3]
    arr=[correct]+wrong
    k=i%4; arr=arr[k:]+arr[:k]
    return arr, 'ABCD'[arr.index(correct)]
for n,(title,slug,facts) in chapters.items():
    narrow=n in (10,20); count=10 if narrow else 12
    lines=[f'---\ntitle: "{title} — Questions"\nsubject: history\nchapter: {n}\ntags: [question-bank, ssc, history]\ntopic_id: [history.{slug}.questions]\n---\n',f'# {title} — Questions\n\n> Source: [[../../history/{n:02d} - {title}.md|{title}]]\n']
    for i in range(1,count+1):
        if i<=4: diff='recall'; stem=f'Which statement about {title} is correct?'; correct=facts[i-1]; pool=facts
        elif i<=9: diff='apply'; j=(i-1)%4; stem=f'A student is revising a description from the chapter. Which identification is correct?'; correct=facts[j]; pool=facts
        else: diff='tricky'; j=(i-1)%4; stem=f'Consider the following statement about {title}: which option is accurate?'; correct=facts[j]; pool=facts
        oo,ans=opts(correct,pool,i)
        lines += [f'@qhis.{slug}.q{i} difficulty={diff} subject=history chapter={n}',stem,'']+[f'- {x}) {v}' for x,v in zip('ABCD',oo)]+['@@','', '<details><summary>Answer & explanation</summary>','',f'**Answer: {ans}**','',correct,'',f'**Trap:** The other options are drawn from nearby facts in the same chapter and are easy to confuse when similar rulers, dates or movements are mixed up.','',f'**See also:** [[../../history/{n:02d} - {title}.md#Content|{title} — source chapter]]','</details>','']
    (out/f'{n:02d} - {title} — Questions.md').write_text('\n'.join(lines),encoding='utf-8')
print(f'generated {len(chapters)} files, {sum(10 if n in (10,20) else 12 for n in chapters)} questions')
